before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  - id: "nsloc"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      # - windows
    goarch:
      - amd64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}-{{.ShortCommit}}

archives:
  - id: nsloc-zip
    builds:
      - nsloc
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}-{{ .Arm }}{{ end }}{{ if .Mips }}-{{ .Mips }}{{ end }}"
    format: zip
    files:
      - LICENSE
      - README.md
changelog:
  skip: true

snapshot:
  name_template: "{{ .Tag }}-{{ .ShortCommit }}-next"

